language: python
sudo: false
python:
  - "2.7"
    #  - "3.3" Not yet
install:
  - pip install coveralls
  - ./scripts/setup
script:
  - ./scripts/test
after_success:
  # Report test coverage to coveralls.io
  - coveralls
notifications:
  email: false
