language: python
sudo: false
python:
  - "2.7"
    #  - "3.3" Not yet
before_install:
  # Install the coverage utility and coveralls reporting utility
  - pip install coverage
  - pip install coveralls
  - pip install pep8
  - pep8 --exclude=tests *.py cnxeasybake/
  - pep8 --max-line-length=1000 cnxeasybake/tests
install:
  - python setup.py install
script:
  - coverage run --source=cnxeasybake setup.py test
after_success:
  # Report test coverage to coveralls.io
  - coveralls
notifications:
  email: false
