language: python
sudo: false
python:
  - "2.7"
  - "3.6"
install:
  - CI=true ./scripts/setup
script:
  - ./scripts/test
after_success:
  # Report test coverage to coveralls.io
  - . ./bin/activate && coveralls
notifications:
  email: false
