language: python
sudo: false
python:
  - "2.7"
    #  - "3.3" Not yet
install:
  - ./script/setup
script:
  - ./script/test
after_success:
  # Report test coverage to coveralls.io
  - . ./venv/bin/activate && coveralls
notifications:
  email: false
